SELECT TRUNC(MBC.DTLANC) AS "Dia",
       CTA.CODCTABCOINT AS"Conta Bancária",
       EMP.RAZAOSOCIAL AS "Empresa",
       EMP.CODEMP "Empresa ID",
       MBC.VLRLANC*MBC.RECDESP AS  "Outras Movimentações"
FROM TGFMBC MBC
LEFT JOIN TGFFIN FIN ON FIN.NUBCO = MBC.NUBCO
LEFT JOIN TSICTA CTA ON CTA.CODCTABCOINT = MBC.CODCTABCOINT
LEFT JOIN TSIEMP EMP ON EMP.CODEMP = CTA.CODEMP
WHERE FIN.NUFIN IS NULL 
