SELECT CAST(DTLANC AS DATE) AS "Dia",
       NAT.CODNAT AS "Natureza NV1",
       COALESCE(CTA.CODCTABCOINT, -999) AS "Conta Bancária",
       PAR.CODPARC AS "Parceiro",
       CUS.CODCENCUS AS "Centro de Resultado",
       TPO.CODTIPOPER AS "Tipo de Operação",
       EMP.CODEMP AS "Empresa ID",
       EMP.RAZAOSOCIAL AS "Empresa",
       TIT.CODTIPTIT AS "Tipo de Título ID",
       TIT.DESCRTIPTIT AS "Tipo de Título",
       'N' AS "Provisão ID",
       'Não' AS "Provisão",
       CASE
           WHEN CAST(FIN.DTVENC AS DATE) > CAST(FIN.DHBAIXA AS DATE) THEN 6
           WHEN CAST(FIN.DTVENC AS DATE) < CAST(FIN.DHBAIXA AS DATE) THEN 7
           WHEN CAST(FIN.DTVENC AS DATE) = CAST(FIN.DHBAIXA AS DATE) THEN 8
       END AS "Status ID",
       CASE
           WHEN CAST(FIN.DTVENC AS DATE) > CAST(FIN.DHBAIXA AS DATE) THEN 'Atrasada'
           WHEN CAST(FIN.DTVENC AS DATE) < CAST(FIN.DHBAIXA AS DATE) THEN 'Adiantada'
           WHEN CAST(FIN.DTVENC AS DATE) = CAST(FIN.DHBAIXA AS DATE) THEN 'No vencimento'
       END AS "Status",
       FIN.RECDESP AS "Recdesp ID",
       CASE
           WHEN FIN.RECDESP = 1 THEN 'Receita'
           WHEN FIN.RECDESP = -1 THEN 'Despesa'
           ELSE 'N/A'
       END AS "Recdesp",
       NUFIN AS "Nufin ID",
       NUFIN AS "Nufin",
       CASE
            WHEN FIN.RECDESP = 1 THEN FIN.VLRBAIXA
       END AS "Recebidos",
       CASE
            WHEN FIN.RECDESP = -1 THEN FIN.VLRBAIXA
       END AS "Pagos",
       NULL AS "A Receber",
       NULL AS "A Pagar"
FROM TGFMBC MBC
LEFT JOIN TGFFIN FIN ON FIN.NUBCO = MBC.NUBCO
LEFT JOIN TGFPAR PAR ON PAR.CODPARC = FIN.CODPARC
LEFT JOIN TGFNAT NAT ON NAT.CODNAT = FIN.CODNAT
LEFT JOIN TSICUS CUS ON CUS.CODCENCUS = FIN.CODCENCUS
LEFT JOIN TSIEMP EMP ON EMP.CODEMP = FIN.CODEMP
LEFT JOIN TGFTOP TPO ON TPO.CODTIPOPER = FIN.CODTIPOPER AND FIN.DHTIPOPER = TPO.DHALTER
LEFT JOIN TGFTIT TIT ON TIT.CODTIPTIT = FIN.CODTIPTIT
LEFT JOIN TSICTA CTA ON CTA.CODCTABCOINT = FIN.CODCTABCOINT
WHERE FIN.DHBAIXA IS NOT NULL
    AND FIN.NUFIN IS NOT NULL /* BAIXAS */
    
UNION ALL

SELECT CAST(DTVENC AS DATE) AS "Dia",
       NAT.CODNAT AS "Natureza NV1",
       COALESCE(CTA.CODCTABCOINT, -999) AS "Conta Bancária",
       PAR.CODPARC AS "Parceiro",
       CUS.CODCENCUS AS "Centro de Resultado",
       TPO.CODTIPOPER AS "Tipo de Operação",
       EMP.CODEMP AS "Empresa ID",
       EMP.RAZAOSOCIAL AS "Empresa",
       TIT.CODTIPTIT AS "Tipo de Título ID",
       TIT.DESCRTIPTIT AS "Tipo de Título",
       FIN.PROVISAO AS "Provisão ID",
       CASE
           WHEN FIN.PROVISAO = 'N' THEN 'Não'
           ELSE 'Sim'
       END AS "Provisão",
       CASE
           WHEN DATEDIFF(DAY, GETDATE(), FIN.DTVENC) >= 0 THEN 1
           WHEN DATEDIFF(DAY, GETDATE(), FIN.DTVENC) BETWEEN -7 AND -1 THEN 2
           WHEN DATEDIFF(DAY, GETDATE(), FIN.DTVENC) BETWEEN -15 AND -8 THEN 3
           WHEN DATEDIFF(DAY, GETDATE(), FIN.DTVENC) BETWEEN -30 AND -16 THEN 4
           WHEN DATEDIFF(DAY, GETDATE(), FIN.DTVENC) < -30 THEN 5
       END AS "Status ID",
       CASE
           WHEN DATEDIFF(DAY, GETDATE(), FIN.DTVENC) >= 0 THEN 'Em Dia'
           WHEN DATEDIFF(DAY, GETDATE(), FIN.DTVENC) BETWEEN -7 AND -1 THEN 'Venceu nos últimos 7 Dias'
           WHEN DATEDIFF(DAY, GETDATE(), FIN.DTVENC) BETWEEN -15 AND -8 THEN 'Venceu nos últimos 15 Dias'
           WHEN DATEDIFF(DAY, GETDATE(), FIN.DTVENC) BETWEEN -30 AND -16 THEN 'Venceu nos últimos 30 Dias'
           WHEN DATEDIFF(DAY, GETDATE(), FIN.DTVENC) < -30 THEN 'Venceu a mais de 30 Dias'
       END AS "Status",
       FIN.RECDESP AS "Recdesp ID",
       CASE
           WHEN FIN.RECDESP = 1 THEN 'Receita'
           WHEN FIN.RECDESP = -1 THEN 'Despesa'
           ELSE 'N/A'
       END AS "Recdesp",
       NUFIN AS "Nufin ID",
       NUFIN AS "Nufin",
       NULL AS "Recebidos",
       NULL AS "Pagos",
       CASE
          WHEN FIN.RECDESP = 1 THEN VLRDESDOB
       END AS "A Receber",
       CASE
          WHEN FIN.RECDESP = -1 THEN VLRDESDOB
       END AS "A Pagar"
FROM TGFFIN FIN
LEFT JOIN TGFPAR PAR ON PAR.CODPARC = FIN.CODPARC
LEFT JOIN TGFNAT NAT ON NAT.CODNAT = FIN.CODNAT
LEFT JOIN TSICUS CUS ON CUS.CODCENCUS = FIN.CODCENCUS
LEFT JOIN TSIEMP EMP ON EMP.CODEMP = FIN.CODEMP
LEFT JOIN TGFTOP TPO ON TPO.CODTIPOPER = FIN.CODTIPOPER AND FIN.DHTIPOPER = TPO.DHALTER
LEFT JOIN TGFTIT TIT ON TIT.CODTIPTIT = FIN.CODTIPTIT
LEFT JOIN TSICTA CTA ON CTA.CODCTABCOINT = FIN.CODCTABCOINT
WHERE FIN.DHBAIXA IS NULL
    AND YEAR(DTVENC) <= 2030
    AND FIN.NUANTBANC IS NULL /* TITULOS EM ABERTO */
